[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
range-collections = "0.2.4"
regex = "1"
grid = "0.9.0"
intervallum = "1.4.0"
gcollections = "1.5.0"
reduce = "0.1.4"
